module.exports = {
    USER_ENTERS: 'USER_ENTERS',
    USER_LEAVES: 'USER_LEAVES',
    USER_ADDED: 'USER_ADDED',
    USER_REMOVED: 'USER_REMOVED',

    MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
    MESSAGES_RECEIVED: 'MESSAGES_RECEIVED',
    MESSAGE_SENT: 'MESSAGE_SENT',

    SOCKET_CONNECTED: 'SOCKET_CONNECTED',
    SOCKET_DISCONNECTED: 'SOCKET_DISCONNECTED',
    SOCKET_ERROR: 'SOCKET_ERROR',
    SOCKET_MESSAGE: 'SOCKET_MESSAGE',

    CREATE_CHANNEL: 'CREATE_CHANNEL',
    DELETE_CHANNEL: 'DELETE_CHANNEL',
    CHANGE_CHANNEL: 'CHANGE_CHANNEL',
    NEW_CHANNEL: 'NEW_CHANNEL',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR',

    INITIALIZE: 'INITIALIZE',
    INITIALIZE_USERS: 'INITIALIZE_USERS',
    INITIALIZE_CHANNELS: 'INITIALIZE_CHANNELS',

    CHANGE_VIEWING_USER: 'CHANGE_VIEWING_USER',
};
