module.exports = {
    USER_ENTERS: 'USER_ENTERS',
    USER_LEAVES: 'USER_LEAVES',
    MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
    MESSAGES_RECEIVED: 'MESSAGES_RECEIVED',
    MESSAGE_SENT: 'MESSAGE_SENT',
    SOCKET_CONNECTED: 'SOCKET_CONNECTED',
    SOCKET_DISCONNECTED: 'SOCKET_DISCONNECTED',
    SOCKET_ERROR: 'SOCKET_ERROR',
    CREATE_CHANNEL: 'CREATE_CHANNEL',
    DELETE_CHANNEL: 'DELETE_CHANNEL',
    CHANGE_CHANNEL: 'CHANGE_CHANNEL'
};
